### PR TITLE
Added green themes

### PR DESCRIPTION
**Pull request by AvanOsch**
green-night is a very simple modification of Poeschl's Red Night theme. (only changed 3 colors)
darkgreen is converted from a theme I made once for "Themeify"

### CODE REVIEW

**Comment by LazeMSS** [comment]
@AvanOsch  i'm working on allowing customizing and having "color schemes" for the themes so I might just include the different color styles for the red night theme - is this okay?

**Comment by AvanOsch** [comment]
@LazeMSS "color schemes" would make the "green-night" theme obsolete. (Excellent feature btw)

The "dark green" theme is totally different though. All the colors in that theme are variables as well.

**Comment by LazeMSS** [comment]
Okay

**Comment by LazeMSS** [comment]
@AvanOsch  could you maybe split the green theme and green-night into two different PR - i can then quickly merge the green theme and maybe add the green night into the next release of UI Customizer

**Comment by AvanOsch** [comment]
@LazeMSS I removed the obsolete theme.
Also found a small bug in red-night css (color: #white)

**Comment by LazeMSS** [comment]
@AvanOsch merged - maybe if you have the time take a look at customizing the menu bar in settings when Responsive mode is on :)

**Comment by LazeMSS** [comment]
@AvanOsch  could you have a look at this: 
https://github.com/LazeMSS/OctoPrint-UICustomizerThemes/issues/9
for your theme?

**Pull request merged**
