### PR TITLE
Add discorded theme

### PR DESCRIPTION
**Pull request by Poeschl**
I started already with the discorded theme.

For now its just the basic theme.

* [x] Extract the base theme
* [ ] ~~❓  Refactor to use variables~~
* [x] Adjust for UICustomizer styles
* [x] Adjust for filemanager plugin
* [x] Adjust for print-time-genius
* [x] Adjust for psucontrol
* [x] Adjust for TopTemp
* [x] Adjust for bedlevelvisualizer
* [x] Ensure supported well elements
* [x] Adjust for PrintJobHistory
* [x] New thumbnail

### CODE REVIEW

**Comment by LazeMSS** [comment]
Awesome. I also wanted to ask you what you thought about and idea allowing the end user to change the css variable colors?

I will try and test this asap btw

**Comment by Poeschl** [comment]
I would really like to allow a change of the CSS variables through the settings Ui. 😉
It would meke customizig the themes easier for the end users.

**Comment by LazeMSS** [comment]
I'm still working on having different color schemes - i'm currently testing it now.

**Comment by Poeschl** [comment]
Nice, really looking forward to it. Will the settings be for colors only? Or also some simple strings?

Was thinking about modifying the terminal height, controlled by a css variable.

**Comment by LazeMSS** [comment]
Color schemes first.

The I will add variable editor where you can specify type: color, string etc

**Comment by Poeschl** [comment]
Unfortunately version 1.6 of Octoprint messes up the styles of the scrollbars.

**Comment by Poeschl** [comment]
The scrollbars are styled with the internal styles. I'm able to overwrite those right now, but the variables are not recognized. 😅

As example look at the blue scrollbar in the settings.

I might fix this later. 😉

**Comment by LazeMSS** [comment]
Ahh I can remove/reset any internal styling if needed

**Comment by Poeschl** [comment]
I will look at it in a follow PR and might come back to change the `html.touchevents` styles of the plugin :).
For now the discorded theme should be ready to rock.

**Comment by LazeMSS** [comment]
image

The tabs are kinda broken :)

**Pull request merged**
