### PR TITLE
first stab at compiling my Themeify less file into UICustomizer theme.

### PR DESCRIPTION
**Pull request by jneilliii**
Setting PR as draft until everything has been flushed out. I believe it has the majority of stuff, but may be missing bits specific to UICustomizer.

### CODE REVIEW

**Comment by LazeMSS** [comment]
Maybe just add the below to fix the settings bar:
```
#UICsettingsMenuNav {
    background-color: rgb(54 57 63);
    background: linear-gradient(180deg, rgb(54 57 63) 0px, rgb(54 57 63) 55px, rgba(255,255,255,0) 100%);
}
```

**Comment by LazeMSS** [comment]
Ps. IT LOOKS AWESOME!

**Comment by jneilliii** [comment]
Added missing rules, one question though. What selector controls this scroll bar?

image

**Comment by LazeMSS** [comment]
```
 /* Track */
html.touchevents #settings_dialog ::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3) !important;
    -webkit-border-radius: 10px !important;
    border-radius: 10px !important;
}

 /* Handle */
html.touchevents #settings_dialog ::-webkit-scrollbar-thumb {
    -webkit-border-radius: 10px !important;
    border-radius: 10px !important;
    background-color: #006dcc !important;
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5) !important;
}
html.touchevents #settings_dialog ::-webkit-scrollbar-thumb:window-inactive {
    background-color: #999999 !important;
}
```

**Comment by jneilliii** [comment]
Thanks @LazeMSS let me know if you see anything else out of place, those changes have been incorporated and adjusted to my personal liking.

**Comment by LazeMSS** [comment]
Any idea why github thinks your css file is a binary ?

**Comment by LazeMSS** [comment]
Ohh and thumbs are just: 400x225

Next version will support larger thumbs but hey the preview option is already there ;)

**Comment by jneilliii** [comment]
> Ohh and thumbs are just: 400x225
> 
> Next version will support larger thumbs but hey the preview option is already there ;)

Do you mean the screenshot thumb? I didn't pay attention.

**Comment by jneilliii** [comment]
Alright @LazeMSS I think I got all the little things tweaked and ready to go. Hit me up of anyone mentions an issue.

**Pull request merged**
