### PR TITLE
Red night improvements

### PR DESCRIPTION
**Pull request by Poeschl**
Made some style-fixes and also introduced a custom scrollbar style (the white scrollbars stick out on a dark design in Chrome.)

;)

### CODE REVIEW

**Comment by LazeMSS** [comment]
AWESOME WORK!

The next version supporting dowloading themes from here will soon be released ;)

**Comment by Poeschl** [comment]
That's good news 😉

**Comment by LazeMSS** [comment]
@Poeschl  could you look into this: https://github.com/LazeMSS/OctoPrint-TopTemp/issues/37
I don't want to change your perfect skin - its based on: https://gionkunz.github.io/chartist-js/getting-started.html

The background color is here:
div.popover.toptempPopover div.TopTempPopoverGraph

**Comment by Poeschl** [comment]
Will look at it 😉

**Comment by LazeMSS** [comment]
@Poeschl could you have a look at this: 
https://github.com/LazeMSS/OctoPrint-UICustomizerThemes/issues/9
for your theme?

**Pull request merged**
